### ISSUE TITLE
check minimal version

### ISSUE THREAD

**Issue by remicollet** [jbboehr/handlebars.c#62]
Could it be possible (if not too much work) to lower dependency on check ?

For now version 0.9.12 is required
RHEL-7 only have version 0.9.9 see https://rpms.remirepo.net/rpmphp/zoom.php?rpm=check

**Comment by remicollet** [comment]
Probably no value... bison >= 3.0.2 required 
RHEL-7 only have version 2.7 see https://rpms.remirepo.net/rpmphp/zoom.php?rpm=bison

**Comment by jbboehr** [comment]
@remicollet We can work around with bison issue; I can commit the generated parsers.

There's a few missing things in check 0.9.9, but I'll see if I can get it to work in degraded mode.

**Comment by jbboehr** [comment]
@remicollet let me know if the latest master works for you. If possible, bison/flex/gperf shouldn't be installed, otherwise the parsers will try to regenerate. If that's not feasible, I'll have to add a switch to disable it.

**Comment by remicollet** [comment]
Thanks for your work on this issue.

Trying 6cff83a452a886b668bab674baa97215edbd0260 on RHEL-7 without flex/bison

Have to downgrade minimal check version required
`sed -e 's/0.9.12/0.9.9/' -i configure.ac`

But build fails (gcc 4.8 or 6.2)
```
/builddir/build/BUILD/handlebars.c-6cff83a452a886b668bab674baa97215edbd0260/bin/handlebarsc.c:287: undefined reference to `handlebars_yy_get_lval'
/builddir/build/BUILD/handlebars.c-6cff83a452a886b668bab674baa97215edbd0260/bin/handlebarsc.c:283: undefined reference to `handlebars_yy_lex'
../src/.libs/libhandlebars.so: undefined reference to `handlebars_yy_get_extra'
../src/.libs/libhandlebars.so: undefined reference to `handlebars_yy_set_extra'
../src/.libs/libhandlebars.so: undefined reference to `handlebars_yy_parse'
../src/.libs/libhandlebars.so: undefined reference to `handlebars_yy_lex_destroy'
../src/.libs/libhandlebars.so: undefined reference to `handlebars_yy_lex_init'
```

**Comment by jbboehr** [comment]
@remicollet The very latest commit should work: https://github.com/jbboehr/handlebars.c/commit/b346c43ff617bbdf5db4159607420bd54b02b8d3

**Comment by remicollet** [comment]
Thanks.
Build is OK (gcc 4.8.5)

```
============================================================================
Testsuite summary for handlebars-c 0.6.3
============================================================================
# TOTAL: 19
# PASS:  19
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

And I was also able to build pecl/handlerbars with PHP 5.6/7.0/7.1/7.2 (including test suite)
