### ISSUE TITLE
test_cache.c:LMDB Cache (Reset):test_lmdb_cache_reset failed (Alpine Linux)

### ISSUE THREAD

**Issue by ncopa** [jbboehr/handlebars.c#71]
test_cache fails after rebuilding handlebars.c with json-c-0.13.1. I don't know if json-c upgrade is related or if the test failure is triggered by something else.

This is Alpine Linux x86_64 

````
Running suite(s): Handlebars Spec
85%: Checks: 7, Failures: 1, Errors: 0
test_cache.c:189:F:LMDB Cache (Reset):test_lmdb_cache_reset:0: Assertion 'vm->buffer->val == "baz"' failed: vm->buffer->val == "", "baz" == "baz"
````

**Comment by ncopa** [comment]
same error happens with json-c 0.12.1 on 32 bit x86

**Comment by jbboehr** [comment]
Strange, I thought we had decided to not include LMDB support in the alpine package: https://github.com/jbboehr/handlebars.c/issues/55#issuecomment-306130496

**Comment by jbboehr** [comment]
To be honest, the LMDB cache backend is inferior to either of the other backends [1] - I would be inclined to remove it or disable it by default.

[1] Unless you need to save every last byte of memory, the simple backend is probably safer and faster, and in a multi-threaded forking environment, the mmap backend is FAR superior, allowing the cache to be shared between all processes and not needing any sort of pointer deserialization.

**Comment by jbboehr** [comment]
I might also note that the executable doesn't using caching at all.

**Comment by jbboehr** [comment]
Should be fixed in master, but master won't compile until this [[0]], or equivalent, is merged.

[0]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/9234
