### ISSUE TITLE
Build failure with [-Werror=format-security]

### ISSUE THREAD

**Issue by remicollet** [jbboehr/handlebars.c#87]
During make test, lot of build failure

ex: ck_abort_msg first arg must be a "format" (a string literal)

ex: 
ck_abort_msg(msg) => ck_abort_msg("%s", msg)

**Comment by remicollet** [comment]
Here is the patch I used for version 0.7.2
https://git.remirepo.net/cgit/rpms/lib/libhandlebars.git/plain/build.patch

Sadly the git master branch have diverged a lot, and cannot be applied properly...
I need to set up a better build env to work on this

**Comment by jbboehr** [comment]
Looks like this is specifically introduced in libcheck 0.15.2 (or maybe 0.15.1, although it looks like it was targeted for 0.15.0, I couldn't replicate it on that version). I'm still on 0.14 and nixpkgs-unstable is still on 0.15.0.

**Comment by jbboehr** [comment]
Thanks for the tip and patch, btw! I'm specifying `-Wformat-security` in my build flags but libcheck only added the printf attribute recently so I didn't catch them.

> I need to set up a better build env to work on this

I hope I'm not causing you too much extra work!

**Comment by remicollet** [comment]
thanks for the quick fix.

> I hope I'm not causing you too much extra work!

No, as I don't start to work on it ;)
